# Generated by Django 5.0.6 on 2025-12-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_postinteraction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinteraction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postinteraction', to='blog.post'),
        ),
    ]
