# Generated by Django 5.0.6 on 2025-12-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedcontent',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Sentiment score: -1.0 (very negative) to +1.0 (very positive)', null=True),
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='score',
            field=models.FloatField(help_text='Combined toxicity score (profanity + hate adjustments)'),
        ),
    ]
