# Generated by Django 5.0.6 on 2025-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_flaggedcontent_sentiment_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flaggedcontent',
            options={'ordering': ['-flagged_at'], 'verbose_name': 'Flagged Content', 'verbose_name_plural': 'Flagged Contents'},
        ),
        migrations.RemoveField(
            model_name='flaggedcontent',
            name='sentiment_score',
        ),
        migrations.AlterField(
            model_name='flaggedcontent',
            name='score',
            field=models.FloatField(),
        ),
    ]
